### ISSUE TITLE
Do not build at startup

### ISSUE THREAD

**Issue by billypon** [microsoft/vscode-arduino#1475] opened 2022-03-16 02:39 UTC
Can I change to not build at startup?
Sometimes, I just want to read code.

**Comment by BelKed** [comment] 2022-03-16 12:34
Seems like duplicate of this issue:
- https://github.com/microsoft/vscode-arduino/issues/1287

**Comment by aleun** [comment] 2022-03-18 21:05
Closing as duplicate of #1287.

**Closed by aleun** 2022-03-18 21:05 UTC
Labels: triage
