### ISSUE TITLE
INO Files defines undefined but can jump to definition

### ISSUE THREAD

**Issue by rnd-ash** [microsoft/vscode-arduino#969] opened 2020-02-16 12:31 UTC
Within Arduino INO files, values that are defined in project level header files make intellisense throw the following error:
![image](https://user-images.githubusercontent.com/14551965/74604669-15502580-50b8-11ea-96bc-bd6ba70e9af6.png)

However, as shown, it appears it is able to jump to definition of the define. Project compilation also works fine without an issue

**Comment by elektronikworkshop** [comment] 2020-02-16 14:04
vscode-arduino does not configure IntelliSense correctly. This is a duplicate of #438 (and many others). I'm currently working on this issue (I'm not associated with the original maintainers though). A beta test should become available in the forthcoming week. See the issue above for more information.

Before filing an issue, please search the existing issues first. This way we can focus on the stuff that matters. Thanks!

Maintainers: Can be closed as duplicate.

**Comment by adiazulay** [comment] 2021-03-22 20:58
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.

**Closed by adiazulay** 2021-03-22 20:58 UTC
Labels: intellisense
