### ISSUE TITLE
build.extra_flags breaks arduino-cli build with "Error: unknown flag: --pref"

### ISSUE THREAD

**Issue by thirtytwobits** [microsoft/vscode-arduino#1282] opened 2021-06-07 16:03 UTC
Platform: OSX Big Sur
arduino-cli version: arduino-cli alpha Version: 0.18.3 Commit: d710b642 Date: 2021-05-21T17:11:27Z
arduino.json:
```json
{
    "sketch": "mysketch.ino",
    "board": "SparkFun:avr:promicro",
    "configuration": "cpu=16MHzatmega32U4",
    "output": "build",
    "buildPreferences": [
        ["build.extra_flags", "-DMYPI=3.14"]
    ]
}
```

Expected:
builds with "-DMYPI" define available in sketeches.

Observed:
```bash
Please see the build logs in output path: /Volumes/workspace/mysketch/build
Error: unknown flag: --pref
Usage:
  arduino-cli compile [flags]

Examples:
  /usr/local/bin/arduino-cli compile -b arduino:avr:uno /home/user/Arduino/MySketch
  /usr/local/bin/arduino-cli compile -b arduino:avr:uno --build-property "build.extra_flags=\"-DMY_DEFINE=\"hello world\"\"" /home/user/Arduino/MySketch
  /usr/local/bin/arduino-cli compile -b arduino:avr:uno --build-property "build.extra_flags=-DPIN=2 \"-DMY_DEFINE=\"hello world\"\"" /home/user/Arduino/MySketch
  /usr/local/bin/arduino-cli compile -b arduino:avr:uno --build-property build.extra_flags=-DPIN=2 --build-property "compiler.cpp.extra_flags=\"-DSSID=\"hello world\"\"" /home/user/Arduino/MySketch

...
```

**Comment by benmcmorran** [comment] 2022-01-19 21:35
Closing as a duplicate of #1268, which should be fixed by #1269.

**Closed by benmcmorran** 2022-01-19 21:35 UTC
