### ISSUE TITLE
IntelliSense auto-generation does not add correct -mmcu compiler argument

### ISSUE THREAD

**Issue by dumbasPL** [microsoft/vscode-arduino#1246] opened 2021-04-30 23:34 UTC
As requested [here](https://github.com/microsoft/vscode-arduino/issues/959#issuecomment-804392754) I would like to reopen this issue. 

MCU-specific code like inline assembly or direct register access will generate false-positive error messages in IntelliSense.

Example of problematic code:
```cpp

//example 1: PRGMEM access
//based on https://www.arduino.cc/reference/en/language/variables/utilities/progmem/
const char signMessage[] PROGMEM = {"This is a test"};
char myChar;
void foo() {
  // read back a char
  for (byte k = 0; k < strlen_P(signMessage); k++) {
    myChar = pgm_read_byte_near(signMessage + k); // this will throw `unknown register name 'r0' C/C++(1118)` but compile just fine
    Serial.print(myChar);
  }
  Serial.println();
}

//example 2: register access
//based on https://www.arduino.cc/en/Reference/PortManipulation
void bar() {
  // sets Arduino pins 1 to 7 as outputs, pin 0 as input
  DDRD = B11111110; // this will throw `identifier "DDRD" is undefined C/C++(20)` but compile just fine

  // sets digital pins 7,5,3 HIGH
  PORTD = B10101000; // this will throw `identifier "PORTD" is undefined C/C++(20)` but compile just fine
}
```

Proposed solution add correct `-mmcu` flag based on currently selected board.
Example for an Arduino UNO board: `-mmcu=atmega328p`

Adding this flag solves all the above-mentioned issues.

**Comment by egcris** [comment] 2021-10-21 22:47
Duplicate of #1279 

vscode-arduino uses [cocopa](https://github.com/elektronikworkshop/cocopa) to parse Arduino's avr-g++ command-line. -D flags work fine but -mmcu are never sent from cocopa to vscode-arduino, as per [cocopa bug 7](https://github.com/elektronikworkshop/cocopa/issues/7) :(

**Closed** 2022-10-24 08:48 UTC
