### ISSUE TITLE
Serial Port dose not send data.

### ISSUE THREAD

**Issue by mustaqmasterstudent** [microsoft/vscode-arduino#1340] opened 2021-09-06 08:43 UTC
I want to read the string input from the user in serial port.

When I use "Arduino: Sent Text to Serial Port". I was not able to send the text to serial port even after hitting the enter.

Is there any way for this. Any alternatives?

**Comment by hlovdal** [comment] 2021-09-16 08:22
This seems to be a duplicate of #1339, can you verify and check if downgrading like mentioned in that issue makes any difference?

**Comment by mustaqmasterstudent** [comment] 2021-09-16 09:16
Yes, I already tried that. 

I tried after downgrading, but it was not even compiling for me. So, I upgraded again. 

Which is also similar issue of #1339 and #1347.

**Comment by hlovdal** [comment] 2021-09-21 22:26
So this issue can be closed as a duplicate then, and all effort be put into #1339 I assume?

**Comment by mustaqmasterstudent** [comment] 2021-09-26 18:58
Okay! I close my issue, as this is just duplicate of #1339 issue.

**Closed** 2021-09-26 18:59 UTC
