### ISSUE TITLE
Output monitor don't shows sketch memory usage

### ISSUE THREAD

**Issue by lozziboy** [microsoft/vscode-arduino#1215] opened 2021-03-24 09:45 UTC
As described in the title, after compiling the sketch, vscode output monitor don't shows sketch memory usage like in the IDE environment (below)

![sketch memory](https://user-images.githubusercontent.com/16566804/112288797-fe520e80-8c8d-11eb-9209-90218d080136.PNG)

**Comment by cth000182** [comment] 2021-03-24 14:37
You can change your Log Level in the settings under the Arduino Extension. It should be "Info" but you can change to "Verbose" - you have to search a bit, but the usage is there.

**Comment by lozziboy** [comment] 2021-03-25 07:30
> You can change your Log Level in the settings under the Arduino Extension. It should be "Info" but you can change to "Verbose" - you have to search a bit, but the usage is there.

That's true.
However it's a big disadvantage the fact that this important information is drowned among hundreds of others, so there is the needs to spend time in searching for it

**Comment by cth000182** [comment] 2021-03-25 11:16
@lozziboy I completely agree! We ran into this yesterday and were wondering why our compiler was not showing the normal information during a build - thought we broke something! Did not know it was an update... 

Hopefully, they can get this resolved as showing the usage is quite important when writing code. If we find a method, I will post here.

**Comment by adiazulay** [comment] 2021-03-26 16:05
Thanks for catching this bug, this likely has to do with how the IntelliSense generates the settings. Will look into this for the next release.

**Comment by iqapps** [comment] 2021-05-31 11:27
Reminder: We got a new release since the last comment here

**Comment by dasfdlinux** [comment] 2021-06-16 14:15
Still missing this percent usage.

**Comment by dealmeal** [comment] 2021-08-28 21:51
> Thanks for catching this bug, this likely has to do with how the IntelliSense generates the settings. Will look into this for the next release.

Please 🙏

**Comment by dasfdlinux** [comment] 2021-10-05 17:24
@adiazulay Can this be marked as a regression and moved higher up in the priority list? At the moment I'm writing my source in Code, and then going to my other monitor where I have the Arduino IDE pulled up for compiling so I can get the program space utilization.

Not to be a grouch, but this has been marked as an issue for over six months. And it's not a feature request, it was the result of a breaking change.

**Comment by jelimoore** [comment] 2021-11-06 23:44
+1. This is a necessary feature for me and not having it is making me slowly crawl back to the Arduino IDE.

**Comment by dasfdlinux** [comment] 2022-01-13 21:11
Thank you, @AlexIII and @benmcmorran!

**Comment by benmcmorran** [comment] 2022-01-15 02:49
This issue has been fixed in the latest release of this extension, which is available in the VS Code extension marketplace.

**Closed by benmcmorran** 2022-01-15 02:49 UTC
Labels: bug

**Comment by SirSydom** [comment] 2022-02-18 09:01
memory usage is not displayed with 0.4.11

**Comment by lozziboy** [comment] 2022-02-18 14:16
> memory usage is not displayed with 0.4.11

That's not true in my case
![image](https://user-images.githubusercontent.com/16566804/154699067-e9711a52-d601-4ff7-ac63-42849a8600ab.png)

**Comment by BelKed** [comment] 2022-02-18 14:18
Probably it's related to this issue:
- https://github.com/microsoft/vscode-arduino/issues/1417

**Comment by hicwic** [comment] 2022-04-27 13:10
thx, English language on arduino IDE does the trick. Was in french, changed to English, restarted VSCode, et memory report is displaying. Thx you

**Comment by hydrafi** [comment] 2023-02-18 08:25
Yes it works, but only if IDE used. Now Ide is deprecated .... with cli the report is displayed only if verbose, but there are too much info... with info flag the report isn't displayed ... is there a solution?

**Comment by SimonArrowhead** [comment] 2024-02-05 20:53
Is there any progress in resolving this issue?

**Comment by matteolavaggi** [comment] 2024-03-23 11:21
Problem still here with last version of VSC + Arduino extension using Arduino CLI and Arduino IDE in english:

`Writing | ################################################## | 100% 0.14s

avrdude: 848 bytes of flash written

avrdude done.  Thank you.

IntelliSense configuration already up to date. To manually rebuild your IntelliSense configuration run "Cmd+Alt+I"
[Done] Uploading sketch 'ArduinoCopilot.ino'`
