### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by love2nerd** [microsoft/vscode-arduino#1122] opened 2020-10-28 18:09 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-arduino`
- Extension Version: `0.3.2`
- OS Version: `Linux arm 5.4.72-v7l `
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :w```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 178,
		"activateCallTime": 126,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vsciot-vscode.vscode-arduino",
				"_lower": "vsciot-vscode.vscode-arduino"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```arning:

**Comment by robotdad** [comment] 2020-10-29 18:46
What is the issue?

**Comment by robotdad** [comment] 2020-11-13 18:52
Closing for now, reopen with details on what the issue is e.g. repro steps with the current behavior and expected behavior.

**Closed by robotdad** 2020-11-13 18:52 UTC
Labels: question
