### ISSUE TITLE
Failed to open serial port

### ISSUE THREAD

**Issue by YuMERA** [microsoft/vscode-arduino#1385] opened 2021-11-07 14:37 UTC
Failed to open serial port COM10 due to error: + Error: spawn UNKNOWN

Version: 1.62.0 (user setup)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:19.949Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT ia32 10.0.19043

The problem has existed since before. I opened an issue here: https://github.com/microsoft/vscode-arduino/issues/1334

**Comment by benmcmorran** [comment] 2022-01-19 01:30
I'm closing this as a duplicate of #1334 because it looks like it's the same problem with 32-bit Windows builds. We're investigating if we can create a 32-bit Windows build of the [serial-monitor-cli](https://github.com/microsoft/serial-monitor-cli).

**Closed by benmcmorran** 2022-01-19 01:30 UTC
Labels: serial
