### ISSUE TITLE
Automatic verify on VSCode startup still non optional on v 0.4.10 preview

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1432] opened 2022-01-24 09:42 UTC
The extension still executes verify when VSCode is started with a project, and it still cannot be prevented.

**Comment by iqapps** [comment] 2022-01-24 09:45
See #1287

**Comment by robotdad** [comment] 2022-02-07 18:33
This seems to be a dupe of #1287. Also, this is not the behavior I'm observing. Perhaps we should keep the discussion on the original issue.

**Closed** 2022-02-07 23:15 UTC
