### ISSUE TITLE
Suddenly can't find arduino IDE

### ISSUE THREAD

**Issue by Proladon** [Microsoft/vscode-arduino#791] opened 2019-03-18 04:20 UTC
Since yesterday,  when i wanna upload the code to board or do others things, it will show 
`Cannot find Arduino IDE. Please specify the "arduino.path" in the User Settings. `
![Image](https://upload.cc/i1/2019/03/25/ZV8jJv.png)

But i have already setting and worked well previously. 
I checked everything settings, it's nothing wrong and i didn't change anything...
like user setting 、 worksapce setting、Folder setting 、Extentsions setting...
every "arduino.path": "D:\\Arduino\\arduino.exe" had set

![Image](https://upload.cc/i1/2019/03/25/7DoqEs.png)
![Image](https://upload.cc/i1/2019/03/25/5pf89V.png)
// 2019/3/25
i had tried ::
```
"D:\\Arduino\\"
"D:\\Arduino"
"D:\\Arduino\\arduino.exe"
```

maybe u will say the arduino path is not in "C:\"
but it did works well previously
is it could be a bug?

**Comment by Sneezry** [comment] 2019-03-22 07:13
Hi @Proladon have you tried `"arduino.path": "D:\Arduino"`?

**Comment by Proladon** [comment] 2019-03-25 05:09
> Hi @Proladon have you tried `"arduino.path": "D:\Arduino"`?

Yeah....didn't works too...

**Comment by Sneezry** [comment] 2019-03-25 05:49
Is there a file named `arduino_debug.exe` in `D:\Arduino` folder?

**Comment by Proladon** [comment] 2019-03-25 06:08
> Is there a file named `arduino_debug.exe` in `D:\Arduino` folder?

yeah, you can see in the image_2. under the arduino.exe

**Comment by Sneezry** [comment] 2019-03-25 07:54
Download the zip file attached, unzip it. Open VS Code, then extension tab, click the three dots on top right cornet, select `Install from VSIX` to install the extension, then run `Arduino Path Dump` command. What result can you get?

![Snipaste_2019-03-25_15-53-28](https://user-images.githubusercontent.com/1621293/54903147-29c28700-4f16-11e9-9604-a369c8166cd8.png)

[vscode-arduino-path-missing-validator-0.0.1.vsix.zip](https://github.com/Microsoft/vscode-arduino/files/3002071/vscode-arduino-path-missing-validator-0.0.1.vsix.zip)

**Comment by Proladon** [comment] 2019-03-25 13:14
> Download the zip file attached, unzip it. Open VS Code, then extension tab, click the three dots on top right corner, select `Install from VSIX` to install the extension, then run `Arduino Path Dump` command. What result can you get?


![Image](https://upload.cc/i1/2019/03/25/nez3Rr.png)
![Image](https://upload.cc/i1/2019/03/25/eDOCcQ.png)
![Image](https://upload.cc/i1/2019/03/25/5FlbsQ.png)

and then it open the Arduino IDE 
![Image](https://upload.cc/i1/2019/03/25/iL6JhZ.png)

**Comment by Sneezry** [comment] 2019-03-25 13:23
Press `F1` to open command palette, the execute `Arduino Path Dump`.

![Snipaste_2019-03-25_21-22-25](https://user-images.githubusercontent.com/1621293/54922966-32ca4d00-4f44-11e9-903b-608543c9e5d7.png)

**Comment by Proladon** [comment] 2019-03-25 13:30
oh..sorry i thought is terminal command lol

i got this:
```
Path from config: D:\Arduino\arduino.exe
  Directory exists: false
  Arduino CLI exists: false

Path from Reg: D:\Arduino
  Directory exists: true
  Arduino CLI exists: true

Path from where command: D:\Arduino\arduino.exe
  Directory exists: false
  Arduino CLI exists: false

Final path: D:\Arduino\arduino.exe
  Directroy exists: false
  Arduino CLI exists: false

Oops, Arduino extension cannot find Arduino CLI :\
```
so i need to use D:\Arduino ?
but i had already tired this  hm...

**Comment by Sneezry** [comment] 2019-03-25 13:34
You can just remove `arduino.path` from your settings, the extension can automatically find it from the registry.

**Comment by Proladon** [comment] 2019-03-25 13:43
> You can just remove `arduino.path` from your settings, the extension can automatically find it from the registry.

OMG.....it works....really dumb (°ཀ°)
it confused me for two weeks....

Anyway, Thanks you very much dude !!! Your really nice person ~

**Comment by Sneezry** [comment] 2019-03-25 13:50
Great! Then I will close this issue. Please feel free to open a new one if you have any other question.

**Closed by Sneezry** 2019-03-25 13:50 UTC

**Comment by bec3x** [comment] 2020-01-16 22:52
Hello! I am having the same issue. I have followed the steps in this thread but it is still not working. Here are my results from the Arduino Path Dump 

![image](https://user-images.githubusercontent.com/44934299/72569659-8b2a5c80-3880-11ea-9599-4bf733a5a3f0.png)

**Comment by me6ran** [comment] 2020-03-22 05:36
Got the same error as @bec3x 
![image](https://user-images.githubusercontent.com/17004677/77243171-5f02c300-6bc4-11ea-8b16-7e0545910125.png)

**Comment by vukyvt2002** [comment] 2020-04-25 14:07
> Got the same error as @bec3x
> ![image](https://user-images.githubusercontent.com/17004677/77243171-5f02c300-6bc4-11ea-8b16-7e0545910125.png)

you have to use the folder contained arduino.exe

**Comment by CarlosA1804** [comment] 2020-08-20 21:32
![image](https://user-images.githubusercontent.com/69991655/90827913-b5566800-e302-11ea-80f2-256fdcc944ce.png)
i have this error

**Comment by cdebel2005** [comment] 2020-09-20 15:31
Just want to precise to some users that if you download the Arduino IDE for **Windows 10**, you will probably end up with a Java version downloaded from the Microsoft Store, which doesn't provide any "arduino.exe".  You got to download the version for Windows 7 of the IDE.  I don't know if there's some way to use the Java version with this extension, i've not searched for that yet.

**Comment by Technopy311** [comment] 2021-06-03 03:11
Hello people, i got a possible solution that worked for me. Like now in windows 10 you must install th IDE from the Microsoft Store, vscode had issues detecting arduino and all that stuff. What i've made to solve the problem, was to download the arduino ide from the official site, but selecting the zip file option, for windows. 

Go to the [Official PAge](https://www.arduino.cc/en/software) and here, choose the "Windows Zip File"  option. I´ve downloaded it, and then i moved the zip file into my documents folder, in it, i extracted the zip file.

Then i went to the vscode settings for the Arduino extension, and in the "Arduino: Path" i entered the path, like this "C:\Users\YOUR-USER\Documents\arduino-1.8.15\" (without the two " )  this can be done with any directory, but keep in mind that the path is without the "arduino.exe", it is just the location. 

Then in the Arduino: Command Path, you just need to put "arduino_debug.exe", but with no path, because the extension uses the path we gave it before. Lastly, you just close vscode, and open it again, it should give no errors.

**Comment by Magnum164** [comment] 2021-07-10 20:23
Wanted to leave a comment I had the same issue, this thread helped but I had to gleam through until I found the problem. My problem was not realizing that the setting arduino.commandPath was actually looking for the single exe for the debug, arduino_debug.exe. I think if MS updated the help info to make that clearer it would resolve this issue for everyone. To me a command path is not the same as a executable file.

**Comment by Flipped199** [comment] 2022-03-24 05:11
Hello, I have the same problem, but after referring to your message, I got the following result, my ide version is 2.0.0.rc5, cli is 0.21.0, is it caused by version incompatibility?
![image](https://user-images.githubusercontent.com/40631465/159846601-f95d7c2e-cd52-40d4-99c1-312c23b9afe0.png)
![image](https://user-images.githubusercontent.com/40631465/159846625-4aa37140-de9f-4bbd-920f-2a73c6bd2c1a.png)
