### ISSUE TITLE
error navigation 

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode-arduino#882] opened 2019-08-24 08:58 UTC
This is a featured request.
Maybe this feature already exists then it does not work for me.

If an Arduino Sketch is verified and an error is found in the code it is not possible to easily navigate to the position in the Arduino code. I.e. it does not appear in the ‚Problems‘ section.

**Comment by zunhu** [comment] 2019-08-26 07:29
Hi Maziac, Arduino has highlights for error code. see screenshot. are you talking about this?
use scrollbar can go to the position  of code.

![20190826142839](https://user-images.githubusercontent.com/40815873/63669944-fad67700-c80d-11e9-878d-b05cbc2ca36d.jpg)

**Comment by maziac** [comment] 2019-08-26 08:24
How does it work?
Here is the screenshot from my project:
There are no squiggles.
![Bildschirmfoto 2019-08-26 um 10 17 35](https://user-images.githubusercontent.com/3081973/63676304-f2b91000-c7ea-11e9-8b43-89cc55c5e42b.jpg)

Originally I was searching for a way similar to e.g. typescript (or C++) error/problem handling.
See following screenshots:
![Bildschirmfoto 2019-08-26 um 10 21 22](https://user-images.githubusercontent.com/3081973/63676473-4deb0280-c7eb-11e9-9538-1af88f36b8f3.jpg)

![Bildschirmfoto 2019-08-26 um 10 21 34](https://user-images.githubusercontent.com/3081973/63676494-593e2e00-c7eb-11e9-94f3-e41e7fa14bea.jpg)

After "compiling" (transpiling) the 'problemMatcher' parses the compiler-output and creates 'problems' in the corresponding tab.
If selecting one of the problems the cursor is directly moved to that file and line.

**Comment by zunhu** [comment] 2019-08-27 02:56
Even you don't compiling\verfiy code, input squiggles that parser will show red wavy line.
If you need to select one of the problems and the cursor is directly moved to that file and line, you need to do compiling\verfiy code first, this is by design.

**Comment by maziac** [comment] 2019-08-27 09:43
Two issues here:
a) As you can see from my first screenshot: there are no squiggles from the parser.
b) I would like to see the error in the 'problems tab'.

For b): Is this somehow supported by the extension.
And for a): It does not work.

**Comment by zunhu** [comment] 2019-08-29 03:00
I see, I met same issue before (it is temporary issue), it works sometimes.
I marked as a bug, but not blocking issue.
for workaround, as I said you can do verify or compile code first.

**Comment by maziac** [comment] 2019-08-29 12:57
Could you maybe explain to what of the both issues you are answering. a) or b).
For me it seems that a) is not supported by the extension. Is this correct?
And for b): it does not change anything if I do a verify. Could you please give a step-by-step description.

**Comment by zunhu** [comment] 2019-08-30 07:40
a) squiggles will show and without any execution, I'm not sure it is Arduino Extension issue for VSCode issue. just one time no show during my testing.
b) Yes, it is in problem's tab, I misunderstanding before. no need to do verfiy.

![image](https://user-images.githubusercontent.com/40815873/64002386-7b61e400-cb3c-11e9-8879-2c8a1f86d921.png)

**Closed** 2019-09-09 08:20 UTC
